### ISSUE TITLE
PHP compiler plugin

### ISSUE THREAD

**Issue by marlun** [pgdouyon/vim-accio#19]
I've just installed vim-accio and tried running `:Accio php` on a php file I know has parse errors.

``` php
<?php
$a = 1
var_dump($a)
```

but got the following errors

``` vim
Error detected while processing function accio#accio..<SNR>49_start_job:
line    4:
E216: No such group or event: JobActivity accio_php_global call <SID>job_handler('php', 'global')
line    5:
E118: Too many arguments for function: jobstart
```

My neovim version info:

```
NVIM 0.0.0-alpha+201504060149 (compiled Apr  6 2015 10:58:42)
Commit: 0af7c8f62412d6e3ceb6f10169ef5ea3b70868e5
```

**Comment by pgdouyon** [comment]
You must be running the latest version of Neovim.  The job-control API was recently updated and I haven't had a chance to update Accio to it yet (#16).  I'll push out a fix for that later today.

**Comment by pgdouyon** [comment]
I've updated Accio to the new job-control API.  Can you pull down the new changes and try running the command again?

**Comment by marlun** [comment]
I've updated but I'm still not getting any reaction. Maybe I'm using/running it the wrong way?

If I run `php -lq test.php` which is what the vim php compiler plugin runs (I believe) I get the following output:

```
~$ php -lq test.php

Parse error: parse error in test.php on line 4
Errors parsing test.php
```

If I use vim without Accio and run `:compiler php` and then `make %` the quickfix list gets the following content:

```
test.php|4 error| parse error
```

If I start vim with Accio installed and run `:Accio php` or `:Accio php %` nothing happends.

**Comment by pgdouyon** [comment]
Hmm I can't reproduce the issue.  The correct command to run is `:Accio php %`, can you try with a minimal vimrc that only loads Accio.  Something like the following example, with vim-plug's API replaced with the plugin manager you use:

``` vim
call plug#begin('~/.vim/bundle')
Plug 'pgdouyon/vim-accio'
call plug#end()
```

Also can you reply with your OS and the output of `:version`

**Comment by marlun** [comment]
I did what you asked and it started working, added all the other plugins back and it's still working. Not sure what i did before when it wasn't working.

**Comment by pgdouyon** [comment]
Yea that's really strange, glad I could help though and let me know if anything else comes up.  To be honest I'm still not 100% sure that race conditions aren't possible using the job-control API so it could be some really subtle bug.
